name: api-gateway

image:
  repository: gcr.io/ecommerce/api-gateway
  tag: "1"

replicaCount: 2

container:
  port: 8080

ingress:
  enabled: true
  host: ecommerce.example.com

istio:
  enabled: true