replicaCount: 2

image:
  repository: docker.io/avkhaladkar1991/payment-service
  tag: "12"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8084

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: false
  host: payment.example.com